/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thinkWell;

import java.awt.Frame;
import java.sql.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author claudinei
 */
public class Perguntas extends javax.swing.JDialog {

    /**
     * Creates new form Perguntas
     */

    int cod = 0;
    String Pergunta;
    String respC;
    List respostas = new ArrayList();
    String btnSelecionado;
    PerguntasDAO dao;
    String altC;

    public Perguntas(Frame f, boolean dialog) {
        super(f, dialog);
        initComponents();
        this.setLocationRelativeTo(null);

        btgResp.add(rbtAlt1);
        btgResp.add(rbtAlt2);
        btgResp.add(rbtAlt3);
        btgResp.add(rbtAlt4);
        btgResp.add(rbtAlt5);
        AddPergunta();
        AddRespostas();
         aPanel1.setImage("/img/lousa.png");

    }

    private void AddPergunta() {
        try {
            dao = new PerguntasDAO();
            Pergunta = dao.selecionar();
            txtPergunta.setText(Pergunta);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }

    private void AddRespostas() {
        List respE = new ArrayList();
        try {
            RespostasDAO re = new RespostasDAO();
            respC = re.RespC(dao);
            respE = re.RespE(dao);

            respostas.add(respC);
            respostas.add(respE.get(0));
            respostas.add(respE.get(1));
            respostas.add(respE.get(2));
            respostas.add(respE.get(3));

            Collections.shuffle(respostas);

            rbtAlt1.setText((String) respostas.get(0));
            rbtAlt2.setText((String) respostas.get(1));
            rbtAlt3.setText((String) respostas.get(2));
            rbtAlt4.setText((String) respostas.get(3));
            rbtAlt5.setText((String) respostas.get(4));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }

    private boolean botaoSelec() {
        boolean se = false;

        if (rbtAlt1.isSelected()) {
            btnSelecionado = rbtAlt1.getText();
            se = true;
        } else if (rbtAlt2.isSelected()) {
            btnSelecionado = rbtAlt2.getText();
            se = true;
        } else if (rbtAlt3.isSelected()) {
            btnSelecionado = rbtAlt3.getText();
            se = true;
        } else if (rbtAlt4.isSelected()) {
            btnSelecionado = rbtAlt4.getText();
            se = true;
        } else if (rbtAlt5.isSelected()) {
            btnSelecionado = rbtAlt5.getText();
            se = true;
        }
        return se;
    }

    public boolean errouAcertou() {
        boolean re;

        if (btnSelecionado.equals(respC)) {
            re = true;
        }else {
            if (respC.equals(rbtAlt1.getText())) {
                altC = "A";
            }else if (respC.equals(rbtAlt2.getText())) {
                altC = "B";
            }else if (respC.equals(rbtAlt3.getText())) {
                altC = "C";
            }else if (respC.equals(rbtAlt4.getText())) {
                altC = "D";
            }else if (respC.equals(rbtAlt5.getText())) {
                altC = "E";
            }
            re = false;
        }
        return re;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgResp = new javax.swing.ButtonGroup();
        aPanel1 = new thinkWell.APanel();
        btnConfirmar = new javax.swing.JButton();
        rbtAlt5 = new javax.swing.JRadioButton();
        rbtAlt4 = new javax.swing.JRadioButton();
        rbtAlt3 = new javax.swing.JRadioButton();
        rbtAlt2 = new javax.swing.JRadioButton();
        rbtAlt1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPergunta = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Frame02"); // NOI18N
        setUndecorated(true);
        setType(java.awt.Window.Type.UTILITY);

        btnConfirmar.setText("Confirmar Resposta");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        rbtAlt5.setText("jRadioButton5");

        rbtAlt4.setText("jRadioButton4");

        rbtAlt3.setText("jRadioButton3");

        rbtAlt2.setText("jRadioButton2");

        rbtAlt1.setText("jRadioButton1");

        txtPergunta.setColumns(20);
        txtPergunta.setLineWrap(true);
        txtPergunta.setRows(5);
        txtPergunta.setWrapStyleWord(true);
        txtPergunta.setBorder(null);
        txtPergunta.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPergunta.setEnabled(false);
        jScrollPane1.setViewportView(txtPergunta);

        jLabel1.setText("A)");

        jLabel2.setText("B)");

        jLabel3.setText("C)");

        jLabel4.setText("D)");

        jLabel5.setText("E)");

        javax.swing.GroupLayout aPanel1Layout = new javax.swing.GroupLayout(aPanel1);
        aPanel1.setLayout(aPanel1Layout);
        aPanel1Layout.setHorizontalGroup(
            aPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aPanel1Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(aPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtAlt5))
                    .addGroup(aPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtAlt4))
                    .addGroup(aPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtAlt3))
                    .addGroup(aPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtAlt1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(aPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtAlt2)))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirmar)
                .addGap(28, 28, 28))
        );
        aPanel1Layout.setVerticalGroup(
            aPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aPanel1Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(aPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rbtAlt1))
                .addGap(18, 18, 18)
                .addGroup(aPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rbtAlt2))
                .addGap(18, 18, 18)
                .addGroup(aPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rbtAlt3))
                .addGap(18, 18, 18)
                .addGroup(aPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rbtAlt4))
                .addGap(18, 18, 18)
                .addGroup(aPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rbtAlt5))
                .addGap(157, 157, 157)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(aPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        boolean se = botaoSelec();
        if (se == true) {
        boolean re = errouAcertou();
            if (re == true) {
                JOptionPane.showMessageDialog(this, "Parabéns você acertou!!!!");
            } else {
                JOptionPane.showMessageDialog(this, "Que pena, você errou \n A alternativa correta é: (" + altC + ")");
            }
            this.dispose();
        } else if (se == false) {
            JOptionPane.showMessageDialog(this, "Escolha sua resposta!!");
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perguntas(null,true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private thinkWell.APanel aPanel1;
    private javax.swing.ButtonGroup btgResp;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtAlt1;
    private javax.swing.JRadioButton rbtAlt2;
    private javax.swing.JRadioButton rbtAlt3;
    private javax.swing.JRadioButton rbtAlt4;
    private javax.swing.JRadioButton rbtAlt5;
    private javax.swing.JTextArea txtPergunta;
    // End of variables declaration//GEN-END:variables
}
